# Generated by Django 3.0.3 on 2021-01-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mathsquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=264)),
                ('answer', models.IntegerField()),
                ('optionone', models.IntegerField()),
                ('optiontwo', models.IntegerField()),
                ('optionthree', models.IntegerField()),
                ('optionfour', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Socialquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=264)),
                ('answer', models.IntegerField()),
                ('optionone', models.CharField(max_length=264)),
                ('optiontwo', models.CharField(max_length=264)),
                ('optionthree', models.CharField(max_length=264)),
                ('optionfour', models.CharField(max_length=264)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
